# Generated by Django 5.2 on 2025-05-07 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka', models.CharField(help_text='Zadejte značku auta', max_length=45, verbose_name='Značka auta')),
                ('model', models.CharField(max_length=45, verbose_name='Model dané značky auta')),
                ('rok_vyroby', models.PositiveIntegerField(blank=True, help_text='Zadejte rok vydání (1900 - 2025)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Rok vydání')),
                ('dostupnost', models.BooleanField()),
                ('cena_za_den', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno autora musí být vyplněno!'}, help_text='Zadejte křestní jméno', max_length=45, verbose_name='Jméno zákazníka')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Přijmení autora musí být vyplněno!'}, help_text='Zadejte přijemní', max_length=45, verbose_name='Přijmení zakazníka')),
                ('datum_narozeni', models.DateField(blank=True, null=True, verbose_name='Datum narození')),
                ('email', models.CharField(help_text='Zadejte e-mail', max_length=38, verbose_name='e-mail zákaznika')),
                ('telefon', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Zakazník',
                'verbose_name_plural': 'Zákazníci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Pujcka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_pujceni', models.DateField()),
                ('datum_vraceni', models.DateField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.zakaznik')),
            ],
        ),
        migrations.CreateModel(
            name='Platba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_platby', models.DateField()),
                ('castka', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pujcka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.pujcka')),
            ],
        ),
        migrations.CreateModel(
            name='Servis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('popis_servisu', models.TextField(verbose_name='Popis servisu')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.auto')),
            ],
        ),
    ]
