# Generated by Django 5.2.2 on 2025-06-04 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Auto', 'verbose_name_plural': 'Auta'},
        ),
        migrations.AlterModelOptions(
            name='platba',
            options={'verbose_name': 'Platba', 'verbose_name_plural': 'Platby'},
        ),
        migrations.AlterModelOptions(
            name='pujcka',
            options={'verbose_name': 'Pujcka', 'verbose_name_plural': 'Pujcky   '},
        ),
        migrations.AlterModelOptions(
            name='servis',
            options={'verbose_name': 'Servis      ', 'verbose_name_plural': 'Servisy'},
        ),
        migrations.AlterField(
            model_name='platba',
            name='castka',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Částka'),
        ),
        migrations.AlterField(
            model_name='platba',
            name='datum_platby',
            field=models.DateField(verbose_name='Datum platby'),
        ),
        migrations.AlterField(
            model_name='platba',
            name='pujcka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.pujcka', verbose_name='Půjčka'),
        ),
        migrations.AlterField(
            model_name='pujcka',
            name='datum_vraceni',
            field=models.DateField(blank=True, null=True),
        ),
    ]
