# Generated by Django 5.2.2 on 2025-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_alter_auto_options_alter_platba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platba',
            name='poznamka',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AddField(
            model_name='platba',
            name='zpusob_platby',
            field=models.CharField(choices=[('hotovost', 'Hotovost'), ('karta', 'Platební karta'), ('prevod', 'Bankovní převod')], default='hotovost', max_length=20, verbose_name='Způsob platby'),
            preserve_default=False,
        ),
    ]
