# Generated by Django 5.2.2 on 2025-06-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_platba_poznamka_platba_zpusob_platby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platba',
            name='poznamka',
        ),
        migrations.RemoveField(
            model_name='platba',
            name='zpusob_platby',
        ),
    ]
