# Generated by Django 5.2.2 on 2025-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_remove_platba_poznamka_remove_platba_zpusob_platby'),
    ]

    operations = [
        migrations.AddField(
            model_name='servis',
            name='stav',
            field=models.CharField(choices=[('opraveno', 'Opraveno'), ('probiha', 'Probíhá')], default='opraveno', max_length=20, verbose_name='Stav opravy'),
        ),
    ]
