# Generated by Django 5.2.2 on 2025-06-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_servis_stav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='stav',
            field=models.CharField(choices=[('opraveno', 'Opraveno'), ('probiha', 'Probíhá')], default='probiha', max_length=20, verbose_name='Stav opravy'),
        ),
    ]
