# Generated by Django 5.2.2 on 2025-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_alter_servis_stav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servis',
            name='stav',
            field=models.CharField(choices=[('probiha', 'Probíhá')], default='probiha', max_length=20, verbose_name='Stav opravy'),
        ),
    ]
