# Generated by Django 5.2.2 on 2025-06-05 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_alter_servis_stav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servis',
            name='stav',
        ),
    ]
